#!/bin/sh
#
# Start camera...
#

case "$1" in
  start)
	# Boot camera
	/usr/bin/python3 /etc/cv_cam.py
	# On camera script termination, load a shell
	/bin/sh
	;;
  stop)
	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
